const accountsData = [
    {
      "username": "styleurkill",
      "password": "nicolasdu123",
      "country": "RU",
      "games": [
        "Business Tour - Online Multiplayer Board Game",
        "Metin2",
        "Counter-Strike 2",
        "Dota 2"
      ]
    },
    {
      "username": "poignantcliffsi",
      "password": "dUHrG_vx_b1YJvc",
      "country": "RU",
      "games": [
        "Counter-Strike 2",
        "Destiny 2",
        "PUBG: BATTLEGROUNDS",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "tu7gq1uj0wg3",
      "password": "3&!tFti=E(M!,(<",
      "country": "PK",
      "games": [
        "Dead Frontier 2",
        "Counter-Strike 2",
        "Call of Duty\\u00ae",
        "ARK: Survival Ascended"
      ]
    },
    {
      "username": "u97mvgh823bg",
      "password": "2IzRT1uFq064",
      "country": "TH",
      "games": [
        "Counter-Strike 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "vizixx",
      "password": "Kenneth7!",
      "country": "US",
      "games": [
        "Grand Theft Auto V",
        "Wallpaper Engine",
        "Yu-Gi-Oh! Duel Links",
        "Apex Legends",
        "Dota 2"
      ]
    },
    {
      "username": "MohammadKM94",
      "password": "MohammaD@1373",
      "country": "AR",
      "games": [
        "War Thunder",
        "Grand Theft Auto V",
        "Raft",
        "Soundpad",
        "Sea of Thieves",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "lolsmileyfacez",
      "password": "RuneElder33@!#$",
      "country": "RU",
      "games": [
        "Gotham City Impostors: Free To Play",
        "Loadout",
        "Villagers and Heroes",
        "Anarchy Arcade",
        "Quake Live",
        "Unturned",
        "Famaze"
      ]
    },
    {
      "username": "drivingmarten6776",
      "password": "Ali112000",
      "country": "SE",
      "games": [
        "The Planet Crafter",
        "Spacewar"
      ]
    },
    {
      "username": "grace_remolino",
      "password": "tukloy123",
      "country": "CN",
      "games": [
        "Prime World",
        "Tap Tap Infinity",
        "Counter-Strike 2",
        "Dota 2"
      ]
    },
    {
      "username": "228papuas48",
      "password": "59SchenkeR63?!",
      "country": "RU",
      "games": [
        "Garry's Mod",
        "Grand Theft Auto: San Andreas",
        "Fallout 3",
        "Terraria",
        "The Witcher 2: Assassins of Kings Enhanced Edition",
        "Saints Row: The Third",
        "Shadow Warrior Classic (1997)",
        "Cry of Fear",
        "Tomb Raider",
        "The Forest",
        "PAYDAY 2",
        "World of Guns: Gun Disassembly",
        "Saints Row IV",
        "Dark Deception",
        "Blender",
        "The Witcher 3: Wild Hunt",
        "Dead by Daylight",
        "Brawlhalla",
        "NARUTO SHIPPUDEN: Ultimate Ninja STORM 4",
        "Dying Light",
        "VRChat",
        "Call of Duty: Black Ops III",
        "Life is Strange\\u2122",
        "Mortal Kombat X",
        "Hooligan Vasja: Christmas",
        "McOsu",
        "MadOut2 BigCityOnline",
        "Counter-Strike 2",
        "Valakas Story",
        "Apex Legends",
        "Vecter",
        "\\u0412\\u0417\\u041b\\u041e\\u041c \\u0416\\u041e\\u041f\\u042b",
        "tModLoader",
        "House of Detention",
        "Kill It With Fire: HEATWAVE",
        "Life is Strange 2",
        "Metro 2033",
        "Little Nightmares",
        "One-armed cook",
        "Poppy Playtime",
        "Metro: Last Light Complete Edition",
        "Stress Chess",
        "Half-Life",
        "Nothing",
        "Team Fortress 2",
        "Source Filmmaker"
      ]
    },
    {
      "username": "min1119830557",
      "password": "NrmSmZGuWp",
      "country": "CN",
      "games": [
        "Grand Theft Auto V",
        "Fishing Planet",
        "Human Fall Flat",
        "PUBG: BATTLEGROUNDS",
        "Counter-Strike 2",
        "Deceit",
        "Russian Fishing 4",
        "Professional Fishing",
        "Aimlabs",
        "Tactical Three Kingdoms (3 Kingdoms) - Strategy &amp; War",
        "NARAKA: BLADEPOINT",
        "Bless Unleashed",
        "Conqueror's Blade",
        "Contraband Police: Prologue",
        "\\u9b3c\\u8c37\\u516b\\u8352 Tale of Immortal",
        "Soul Dossier",
        "Team Fortress 2",
        "Dota 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "ChkoupenHagen",
      "password": "humain147",
      "country": "DZ",
      "games": [
        "War Thunder",
        "Path of Exile",
        "Dragons and Titans",
        "Gigantic",
        "Brawlhalla",
        "Business Tour - Online Multiplayer Board Game",
        "Pro Evolution Soccer 2016 myClub",
        "Orcs Must Die! Unchained",
        "High Octane Drift",
        "Resident Evil 7 Teaser: Beginning Hour",
        "Minion Masters",
        "Alien Swarm: Reactive Drop",
        "Yu-Gi-Oh! Duel Links",
        "Spider-Man: Homecoming - Virtual Reality Experience",
        "BRINK",
        "Battlerite Public Test",
        "Battlerite",
        "Ultimate Custom Night",
        "Pixel Strike 3D",
        "Counter-Strike 2",
        "Albion Online",
        "Hello Neighbor Alpha 4",
        "Apex Legends",
        "eFootball PES 2020",
        "Shadow Arena",
        "eFootball PES 2021 SEASON UPDATE"
      ]
    },
    {
      "username": "anqzp908",
      "password": "Y8m29aev12",
      "country": "AR",
      "games": [
        "Grand Theft Auto V",
        "Blender",
        "Fishing Planet",
        "VTube Studio",
        "Goose Goose Duck"
      ]
    },
    {
      "username": "wx813827",
      "password": "Lop90adtlmm",
      "country": "CN",
      "games": [
        "Warframe",
        "PUBG: BATTLEGROUNDS",
        "The Ranger: Lost Tribe",
        "Counter-Strike 2",
        "Among Us"
      ]
    },
    {
      "username": "ub15abiq",
      "password": "ny73ZLDO",
      "country": "SA",
      "games": [
        "Cuphead",
        "Grand Theft Auto V",
        "Turmoil",
        "Wallpaper Engine",
        "Call of Duty: Black Ops III",
        "SUPERHOT VR",
        "Beat Saber",
        "Counter-Strike 2",
        "Vampire: The Masquerade - Bloodhunt",
        "Pummel Party",
        "Aimlabs",
        "Among Us",
        "Ranch Simulator",
        "Apex Legends",
        "Red Dead Redemption 2",
        "Streamer Life Simulator",
        "DEVOUR",
        "Cafe Owner Simulator: Prologue",
        "PICO PARK",
        "Internet Cafe Simulator 2",
        "One-armed cook",
        "Warhammer: Vermintide 2",
        "The Sims\\u2122 4",
        "Team Fortress 2",
        "Source SDK Base 2007",
        "Dota 2",
        "Spacewar",
        "Sniper Elite 4 Dedicated Server",
        "Call of Duty: Black Ops III \\u2013 Mod Tools",
        "It Takes Two Friend's Pass"
      ]
    },
    {
      "username": "nostalji97",
      "password": "1593578MK",
      "country": "TR",
      "games": [
        "Mirror's Edge",
        "War Thunder",
        "Assetto Corsa",
        "Grand Theft Auto V",
        "Robocraft",
        "Brawlhalla",
        "Business Tour - Online Multiplayer Board Game",
        "Squad",
        "Squad - Public Testing",
        "DDNet",
        "Rise of the Tomb Raider",
        "VRChat",
        "Tom Clancy's Ghost Recon\\u00ae Wildlands",
        "Raft",
        "Planet Zoo",
        "Spike Volleyball",
        "Paunch",
        "Mythgard",
        "Pummel Party",
        "Overcooked! 2",
        "Conqueror's Blade",
        "Game Migrated to Another Steam Page",
        "Counter-Strike 2",
        "Mortal Kombat 11",
        "Fall Guys",
        "Arcadius",
        "RISK: Global Domination",
        "Ready or Not",
        "Sea of Thieves",
        "Blackjack Championship",
        "Battlefield 1 \\u2122",
        "Redmatch 2",
        "Agrou",
        "Animaze",
        "Feign",
        "Propnight",
        "Goose Goose Duck",
        "Just Act Natural",
        "Innocence Or Money Season 1 - Episodes 1 to 3",
        "The Sims\\u2122 4",
        "Call of Duty\\u00ae",
        "ENDLESS\\u2122 Legend"
      ]
    },
    {
      "username": "mbgraphic",
      "password": "siemens92",
      "country": "BR",
      "games": [
        "Thief Gold",
        "Enclave",
        "AdVenture Capitalist",
        "Metin2",
        "Unturned",
        "HITMAN\\u2122 2",
        "Counter-Strike 2",
        "Dota 2"
      ]
    },
    {
      "username": "qmps93543",
      "password": "Sd5Xt5Rz6Bk6",
      "country": "AR",
      "games": [
        "Unturned",
        "Rust",
        "The Cycle: Frontier",
        "Counter-Strike 2",
        "Apex Legends",
        "PUBG: BATTLEGROUNDS",
        "Lost Ark"
      ]
    },
    {
      "username": "seucawramsniranlomen",
      "password": "Al37724506",
      "country": "UA",
      "games": [
        "Unturned",
        "Counter-Strike 2",
        "Destiny 2",
        "Apex Legends",
        "PUBG: BATTLEGROUNDS",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "qj0ft9il9mr7",
      "password": "RfETdAowqc",
      "country": "TR",
      "games": [
        "War Thunder",
        "Squad",
        "Squad - Public Testing",
        "Counter-Strike 2",
        "Lost Light",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "haxor4teh1337",
      "password": "RuneElder33@!#$",
      "country": "US",
      "games": [
        "Z1 Battle Royale",
        "H1Z1: Test Server",
        "Counter-Strike 2"
      ]
    },
    {
      "username": "x98_iYsK4I",
      "password": "g3sRaHuP",
      "country": "US",
      "games": [
        "Yosumin!",
        "Snake Pass",
        "PUSS!",
        "Counter-Strike 2",
        "Destiny 2"
      ]
    },
    {
      "username": "sci6jfQ838k7",
      "password": "M0MwAf1J",
      "country": "LY",
      "games": [
        "Fishing Planet",
        "Counter-Strike 2",
        "Hired Ops",
        "Destiny 2",
        "World War 3",
        "Combat Master",
        "1v1.LOL"
      ]
    },
    {
      "username": "iqhu61380",
      "password": "K1kkeli1234",
      "country": "UA",
      "games": [
        "The Cycle: Frontier",
        "Counter-Strike 2",
        "Apex Legends",
        "Red Dead Redemption 2",
        "PUBG: BATTLEGROUNDS",
        "Call of Duty\\u00ae"
      ]
    },
    {
      "username": "arifkhan334",
      "password": "Flipkart34",
      "country": "RU",
      "games": [
        "Path of Exile",
        "Aimlabs",
        "Among Us",
        "Stumble Guys"
      ]
    },
    {
      "username": "thanhnhan0401",
      "password": "Mh20022001",
      "country": "VN",
      "games": [
        "KurtzPel",
        "DRAGON BALL Z: KAKAROT",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "karika2011",
      "password": "Kari1129",
      "country": "GT",
      "games": [
        "GRID 2",
        "Age of Conquest IV",
        "Spooky's Jump Scare Mansion",
        "Fishing Planet",
        "Brawlhalla",
        "3dSunshine",
        "PRO EVOLUTION SOCCER 2017 TRIAL EDITION",
        "Unturned",
        "Friday the 13th: Killer Puzzle",
        "Shark Simulator",
        "Ultimate Custom Night",
        "Aimlabs",
        "Counter-Strike 2",
        "Secret Neighbor Beta",
        "Mobler",
        "Cubico",
        "Elon Simulator 2019",
        "Coloring Game: Little City",
        "Crusader Kings II",
        "BLEACH Brave Souls - 3D Action",
        "Krunker",
        "Yu-Gi-Oh!  Master Duel",
        "Goose Goose Duck",
        "MY HERO ULTRA RUMBLE",
        "Crab Game",
        "PUBG: BATTLEGROUNDS",
        "Lost Ark",
        "Stumble Guys",
        "Poppy Playtime",
        "The Riflemen",
        "1v1.LOL",
        "Black Desert",
        "Team Fortress 2",
        "Source SDK Base 2007",
        "Spacewar"
      ]
    },
    {
      "username": "mulkuma20896",
      "password": "hoa7604321",
      "country": "VN",
      "games": [
        "Rec Room",
        "Onmyoji",
        "Counter-Strike 2"
      ]
    },
    {
      "username": "80895420",
      "password": "21165669",
      "country": "CN",
      "games": [
        "Counter-Strike 2",
        "PUBG: BATTLEGROUNDS",
        "Dark and Darker"
      ]
    },
    {
      "username": "pointlessambitiousgerbil",
      "password": "Firstjeans58",
      "country": "IE",
      "games": [
        "Counter-Strike 2",
        "Lost Ark",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "Cu8Oh6Op0El5",
      "password": "Wu0Cn1We0Up6",
      "country": "UY",
      "games": [
        "Grand Theft Auto V",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "ydayyreld39",
      "password": "0N7QaQJSB",
      "country": "RU",
      "games": [
        "Counter-Strike 2",
        "Hired Ops",
        "Apex Legends",
        "Dota 2"
      ]
    },
    {
      "username": "profectian20",
      "password": "verituba1",
      "country": "BR",
      "games": [
        "Hotline Miami 2: Wrong Number",
        "The Long Dark",
        "Brawlhalla",
        "Wallpaper Engine",
        "Hidden Folks",
        "Paladins",
        "Paladins - Public Test",
        "Raft",
        "South Park The Fractured But Whole",
        "Aimlabs",
        "Counter-Strike 2",
        "Yet Another Zombie Defense",
        "Bloons TD 6",
        "Mortal Kombat 11",
        "Sea of Thieves",
        "Hades",
        "Cozy Grove",
        "FIFA 22",
        "Ultimate Epic Battle Simulator",
        "Idle Slayer",
        "Crab Game",
        "Hextech Mayhem: A League of Legends Story\\u2122",
        "Ruined King: A League of Legends Story\\u2122",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "oom321123",
      "password": "oomza5912",
      "country": "TH",
      "games": [
        "Heroes &amp; Generals",
        "Realm Royale Reforged",
        "Realm Royale - Test Server"
      ]
    },
    {
      "username": "yins2020",
      "password": "Avoquerido1.",
      "country": "BR",
      "games": [
        "Counter-Strike 2",
        "Destiny 2"
      ]
    },
    {
      "username": "jackvrp1",
      "password": "Dubs1faze",
      "country": "US",
      "games": [
        "Counter-Strike 2",
        "Apex Legends",
        "Stumble Guys",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "tiditada",
      "password": "kolya14juillet",
      "country": "RU",
      "games": [
        "The Lord of the Rings Online\\u2122",
        "Unturned",
        "Mitos.is: The Game",
        "Counter-Strike 2",
        "POSTAL",
        "Gorilla Tag",
        "Call of Duty\\u00ae: Modern Warfare\\u00ae II - Open Beta"
      ]
    },
    {
      "username": "bagemrecan",
      "password": "E_05530732001",
      "country": "TR",
      "games": [
        "Garry's Mod",
        "Euro Truck Simulator 2",
        "TrackMania Nations Forever",
        "C9",
        "PlanetSide 2",
        "PlanetSide 2 - Test",
        "Warframe",
        "War Thunder",
        "Verdun",
        "Counter-Strike",
        "Team Fortress Classic",
        "Day of Defeat",
        "Deathmatch Classic",
        "Half-Life: Opposing Force",
        "Ricochet",
        "Half-Life",
        "Counter-Strike: Condition Zero",
        "Counter-Strike: Condition Zero Deleted Scenes",
        "Half-Life: Blue Shift",
        "Half-Life 2",
        "Counter-Strike: Source",
        "Half-Life: Source",
        "Day of Defeat: Source",
        "Half-Life 2: Deathmatch",
        "Half-Life Deathmatch: Source",
        "Portal",
        "Left 4 Dead",
        "Left 4 Dead 2",
        "Portal 2",
        "Counter-Strike 2",
        "Papers",
        "Please",
        "Assetto Corsa",
        "PAYDAY 2",
        "Rust",
        "Rocket League",
        "American Truck Simulator",
        "Amnesia: The Dark Descent",
        "Amnesia: A Machine for Pigs",
        "Counter-Strike Nexon",
        "Insurgency",
        "Sven Co-op",
        "METAL GEAR SOLID V: THE PHANTOM PAIN",
        "Just Survive",
        "Just Survive Test Server",
        "Z1 Battle Royale",
        "H1Z1: Test Server",
        "BattleBlock Theater",
        "Robocraft",
        "ArcheAge",
        "Trove",
        "Unturned",
        "Warface: Clutch",
        "Heroes &amp; Generals",
        "DiRT 3 Complete Edition",
        "Primal Carnage",
        "Life is Strange\\u2122",
        "Anomaly Zone",
        "Total War: ATTILA",
        "Arma 3",
        "Sherlock Holmes: The Devil's Daughter",
        "Shower With Your Dad Simulator 2015: Do You Still Shower With Your Dad",
        "Ghost in the Shell: Stand Alone Complex - First Assault Online",
        "Brawlhalla",
        "Knight Online",
        "The Howler",
        "Morphopolis",
        "gravilon",
        "Business Tour - Online Multiplayer Board Game",
        "Dungeon Defenders II",
        "Reveal The Deep",
        "Paladins",
        "Paladins - Public Test",
        "Riders of Icarus",
        "Evolve Stage 2",
        "911 Operator",
        "Atlas Reactor",
        "The Witcher 3: Wild Hunt",
        "TOXIKK",
        "Tiger Knight: Empire War",
        "World of Tanks Blitz",
        "Infestation: The New Z",
        "House Flipper",
        "Ring of Elysium",
        "Realm Royale Reforged",
        "Realm Royale - Test Server",
        "The Lab",
        "KillStreak.tv",
        "She Sees Red",
        "War Trains",
        "STAR WARS\\u2122 Battlefront\\u2122",
        "Battlefield 1 \\u2122",
        "The Council",
        "PUBG: BATTLEGROUNDS",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "Ximmy05",
      "password": "Ximmy05()",
      "country": "IT",
      "games": [
        "Terraria",
        "Warframe",
        "Blacklight: Retribution",
        "theHunter Classic",
        "Trove",
        "Warface: Clutch",
        "Dirty Bomb",
        "Block N Load",
        "Shakes and Fidget",
        "Argo",
        "Black Squad",
        "Yu-Gi-Oh! Duel Links",
        "Unturned",
        "Aimlabs",
        "Counter-Strike 2",
        "stein.world",
        "Spellbreak",
        "Yu-Gi-Oh!  Master Duel",
        "Halo Infinite",
        "Team Fortress 2"
      ]
    },
    {
      "username": "kidatdev1",
      "password": "Opopopop1",
      "country": "ID",
      "games": [
        "Unturned",
        "Counter-Strike 2",
        "Crosshair V2",
        "Horny Villa",
        "Team Fortress 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "thekidjustin",
      "password": "tintin91",
      "country": "US",
      "games": [
        "Brawlhalla",
        "Resident Evil 7 Teaser: Beginning Hour",
        "Metin2",
        "Counter-Strike 2",
        "eFootball PES 2021 SEASON UPDATE",
        "PUBG: BATTLEGROUNDS",
        "Dota 2"
      ]
    },
    {
      "username": "b6tm7seog25g",
      "password": "zo7ifoxjqfFFQA",
      "country": "KZ",
      "games": [
        "Saints Row: The Third",
        "World of Warships",
        "Counter-Strike 2",
        "Crosshair V2"
      ]
    },
    {
      "username": "look_imio_",
      "password": "Cheerre5.",
      "country": "CN",
      "games": [
        "Counter-Strike",
        "Counter-Strike: Condition Zero",
        "Counter-Strike: Condition Zero Deleted Scenes",
        "Garry's Mod",
        "Portal",
        "The Witcher: Enhanced Edition",
        "Spectraball",
        "Portal 2",
        "Terraria",
        "The Witcher 2: Assassins of Kings Enhanced Edition",
        "Bloodline Champions",
        "America's Army 3",
        "Tribes: Ascend",
        "Rusty Hearts",
        "Stronghold Kingdoms",
        "HOMEFRONT Demo",
        "Spiral Knights",
        "Puzzle Pirates",
        "Age of Empires Online",
        "Pandora Saga: Weapons of Balance",
        "War Inc. Battlezone",
        "Memoir '44 Online",
        "MicroVolts Surge",
        "Brawl Busters",
        "Neverwinter",
        "APB Reloaded",
        "World of Battles",
        "Realm of the Mad God Exalt",
        "Magic: The Gathering \\u2013 Tactics",
        "Pox Nora",
        "EverQuest II",
        "America's Army: Proving Grounds",
        "EverQuest Free-to-Play",
        "Gotham City Impostors: Free To Play",
        "Archeblade",
        "Moon Breakers",
        "RaceRoom Racing Experience",
        "Star Conflict",
        "Mabinogi",
        "Dungeon Fighter Online",
        "Atlantica Online",
        "Arctic Combat",
        "C9",
        "The Lord of the Rings Online\\u2122",
        "Super Crate Box",
        "Dwarfs F2P",
        "Dungeon Party",
        "Dungeonland",
        "PlanetSide 2",
        "PlanetSide 2 - Test",
        "District 187",
        "Champions of Regnum",
        "Uncharted Waters Online",
        "Construct 2 Free",
        "Warframe",
        "Ragnarok Online 2",
        "War Thunder",
        "Shadow Warrior Classic (1997)",
        "Arcane Saga Online",
        "Pinball Arcade",
        "Path of Exile",
        "Panzar",
        "Dragon Nest Europe",
        "Dragons and Titans",
        "Fiesta Online",
        "Thinking with Time Machine",
        "Fiesta Online NA",
        "Peggle Extreme",
        "Retro\\/Grade IGF Demo",
        "Between IGF Demo",
        "Mightier",
        "Coil",
        "Moonbase Alpha",
        "Saints Row: The Third - Initiation Station",
        "The Cat and the Coup",
        "Arma 2: Free",
        "Dungeons &amp; Dragons Online\\u00ae",
        "Gear Up",
        "Ragnarok",
        "Age of Conan: Unchained",
        "Age of Conan: Unchained (US Version)",
        "RaiderZ",
        "iPi Mocap Studio 2",
        "iPi Recorder 2",
        "Renaissance Heroes",
        "Forge",
        "Cry of Fear",
        "Ascend: Hand of Kul",
        "Marvel Puzzle Quest",
        "King\\u2019s Bounty: Legions",
        "Elsword",
        "Soldier Front 2",
        "Ohm Studio",
        "Saints Row IV Inauguration Station",
        "GunZ 2: The Second Duel",
        "Toribash",
        "8BitMMO",
        "The Plan",
        "World of Guns: Gun Disassembly",
        "Fistful of Frags",
        "Cannons Lasers Rockets",
        "City of Steam: Arkadia",
        "Conquest of Champions",
        "Dethroned!",
        "HAWKEN",
        "Serena",
        "Terrain Test",
        "You Have to Win the Game",
        "Battle for Graxia",
        "Spiral Knights Preview",
        "Magicka: Wizard Wars",
        "AirMech",
        "Trash TV (demo)",
        "Vanguard: Saga of Heroes F2P",
        "Jagged Alliance Online - Steam Edition",
        "Dogs of War Online - Beta",
        "DCS World Steam Edition",
        "No More Room in Hell",
        "Pinball FX2",
        "The Mighty Quest For Epic Loot",
        "Haunted Memories",
        "Free to Play",
        "Aerena",
        "Grimm",
        "theHunter Classic",
        "Infinity Wars - Animated Trading Card Game",
        "Villagers and Heroes",
        "Narcissu 1st &amp; 2nd",
        "The Forest",
        "Epigenesis",
        "Heroes of Havoc",
        "Sins of a Dark Age",
        "Rocket League",
        "Fortress Forever",
        "Portal 2 Sixense Perceptual Pack",
        "Max Gentlemen",
        "Get Off My Lawn!",
        "The Four Kings Casino and Slots",
        "Spintires\\u00ae",
        "La Tale",
        "Grand Theft Auto V",
        "Insurgency",
        "Munin",
        "Metro 2033 Redux",
        "Metro: Last Light Redux",
        "Viktor",
        "Super Trench Attack!",
        "Warface: Clutch",
        "Counter-Strike 2",
        "Dirty Bomb",
        "Razenroth",
        "Resident Evil Revelations 2",
        "DARK SOULS\\u2122 II: Scholar of the First Sin",
        "Crazy Machines 3",
        "The Witcher 3: Wild Hunt",
        "Fate Tectonics",
        "SMITE",
        "SMITE - Public Test",
        "Greyfox",
        "Secret Of Magia",
        "Destiny Warriors",
        "Legend of Mysteria",
        "Wallpaper Engine",
        "The Chosen RPG",
        "DARK SOULS\\u2122 III",
        "Paladins",
        "Paladins - Public Test",
        "World of Tanks Blitz",
        "Rock 'N' Roll Defense",
        "Razortron 2000",
        "Planes",
        "Bullets and Vodka",
        "Cyberhunt",
        "The Last NightMary - A Lenda do Cabe\\u00e7a de Cuia",
        "Storm of Spears",
        "UNO",
        "Subterra",
        "Fated Souls 2",
        "Carton",
        "MONMUSU",
        "Black Squad",
        "World of Warships",
        "League of Maidens",
        "EVE Online",
        "Power Hover",
        "Blood of Steel",
        "Chosen 2",
        "PUBG: BATTLEGROUNDS",
        "PC Building Simulator",
        "Car Mechanic Simulator 2018",
        "Pixel Shooter",
        "CS2D",
        "Tales of Blood and Sand",
        "Unturned",
        "Splitgate",
        "Doki Doki Literature Club",
        "SCP: Secret Laboratory",
        "Battle of Frigates",
        "Soundpad",
        "Deceit",
        "Dead Frontier 2",
        "Robot Warriors",
        "War Robots",
        "8-in-1 IQ Scale Bundle",
        "Ironsight",
        "GLAD VALAKAS SIMULATOR",
        "Trivia Vault Football Trivia",
        "Realm Royale Reforged",
        "Realm Royale - Test Server",
        "Z1 Battle Royale",
        "H1Z1: Test Server",
        "Escape From Tethys",
        "DARK SOULS\\u2122: REMASTERED",
        "Simple Sailing",
        "Rogue Company",
        "Aimlabs",
        "Metro Exodus",
        "Metro Exodus Enhanced Edition",
        "\\u8da3\\u62fc\\u62fc\\uff1a\\u8096\\u50cf\\u753b Pleasure Puzzle:Portrait",
        "Among Us",
        "DEAD OR ALIVE Xtreme Venus Vacation",
        "Minion Masters",
        "Nyasha",
        "Dota Underlords",
        "\\u4e9a\\u5229\\u5229\\u4e9a\\u7684\\u7cbe\\u7075\\u4eec ALILIA",
        "Peekaboo",
        "BLOCKADE",
        "Phantasy Star Online 2 New Genesis",
        "Nyasha Land of Elves",
        "Albion Online",
        "Desire Gambling House\\/\\u6b32\\u671b\\u8d4c\\u9986",
        "OMON Simulator",
        "Hired Ops",
        "Pretty Angel",
        "NBA 2K20",
        "Moe Era",
        "Destiny 2",
        "Valakas Story",
        "Apex Legends",
        "Stay Out",
        "Will To Live Online",
        "\\u526f\\u4f5c\\u7528\\u4e4b\\u77b3 (Tlicolity Eyes)",
        "Zup! Z",
        "Bless Unleashed",
        "Shop Titans",
        "Headsnatchers",
        "Tomb Raider",
        "Lara Croft and the Temple of Osiris",
        "Kidnapped Girl",
        "GWENT: The Witcher Card Game",
        "Conqueror's Blade",
        "Helltaker",
        "House of Detention",
        "Forza Horizon 4",
        "Total War: SHOGUN 2",
        "10 Second Ninja X",
        "Pianistic",
        "\\u96c0\\u9b42\\u9ebb\\u5c06(MahjongSoul)",
        "Action Taimanin",
        "Super Mecha Champions",
        "Krunker",
        "BustyBiz",
        "\\u6597\\u7f57\\u5927\\u9646-\\u738b\\u56fd\\u5370\\u8bb0",
        "College Kings - The Complete Season",
        "Draw &amp; Guess",
        "Til Nord",
        "Christmas Mosaic Puzzle",
        "Soul Dossier",
        "Coloring Game 4",
        "Crowalt: Traces of the Lost Colony - Prologue",
        "Grey Instinct",
        "Bro Falls: Ultimate Showdown",
        "Mahjong Carnaval 2",
        "Cloud Bashers DX",
        "\\u505a\\u4e2a\\u597d\\u68a6",
        "Evaverse",
        "\\u679d\\u6c5f\\u5f80\\u4e8b",
        "Captain Bones: Prologue",
        "Reminiscence",
        "\\u8bdb\\u5929\\u8bb0",
        "\\u5951\\u7075\\u4e4b\\u7ea6",
        "The Plane Effect Prologue",
        "natsuno-kanata - beyond the summer",
        "\\u7b2c\\u4e03\\u53f7\\u5217\\u8f66 - Train No. 7",
        "Team Fortress 2",
        "Dota 2",
        "Alien Swarm",
        "A New Beginning - Final Cut",
        "A Fistful of Gun",
        "7 Days to Die",
        "1954 Alcatraz",
        "#KILLALLZOMBIES",
        "A Year Of Rain",
        "AER Memories of Old",
        "Agatha Christie - The ABC Murders",
        "Ace of Protectors",
        "1",
        "000 Heads Among the Trees",
        "AI: Rampage",
        "24 Hours 'til Rescue",
        "50 years",
        "A Trip to Yugoslavia: Director's Cut",
        "123 Slaughter Me Street 2",
        "1943 Deadly Desert",
        "AEGYPTUS",
        "akda",
        "Achievement Clicker 2018",
        "\\u2605 Fallalypse \\u2605 Death or Cress \\u265d",
        "Achievement printer",
        "7-in-1 Brain Sharpness Bundle"
      ]
    },
    {
      "username": "ex60qNJT",
      "password": "fp47HDGT",
      "country": "RU",
      "games": [
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest"
      ]
    },
    {
      "username": "jtitar3",
      "password": "Gg321321321",
      "country": "PH",
      "games": [
        "Apex Legends",
        "3on3 FreeStyle: Rebound",
        "PUBG: BATTLEGROUNDS",
        "Farlight 84",
        "Poppy Playtime",
        "Idol Party",
        "Dota 2"
      ]
    },
    {
      "username": "xxcesarxx19",
      "password": "956575626Ss",
      "country": "PL",
      "games": [
        "Sven Co-op",
        "Half-Life 2: Update",
        "Counter-Strike 2",
        "Half-Life 2",
        "Half-Life 2: Deathmatch",
        "Half-Life Deathmatch: Source",
        "Dota 2"
      ]
    },
    {
      "username": "Endrew017",
      "password": "@Endrew13",
      "country": "BR",
      "games": [
        "Counter-Strike 2",
        "Destiny 2",
        "Apex Legends",
        "Shatterline"
      ]
    },
    {
      "username": "WellgroomedMellowQuail",
      "password": "Damphill63",
      "country": "US",
      "games": [
        "Knight Online",
        "Metin2",
        "Counter-Strike 2",
        "Dota 2"
      ]
    },
    {
      "username": "awakedarkreindeer",
      "password": "Scaryboat50",
      "country": "US",
      "games": [
        "Brawlhalla",
        "Knight Online",
        "Metin2",
        "Counter-Strike 2",
        "Dota 2"
      ]
    },
    {
      "username": "grumpyBoa572",
      "password": "RkBGxEfywNbQ",
      "country": "UA",
      "games": [
        "Tom Clancy's Rainbow Six Siege",
        "Tom Clancy's Rainbow Six Siege - Test Server",
        "VRChat"
      ]
    },
    {
      "username": "cadusting",
      "password": "Calixto21",
      "country": "US",
      "games": [
        "Garry's Mod",
        "Grand Theft Auto V",
        "Five Nights at Freddy's",
        "Five Nights at Freddy's 2",
        "NARUTO SHIPPUDEN: Ultimate Ninja STORM 4",
        "Wallpaper Engine",
        "Soundpad",
        "Secret Neighbor",
        "Ultimate Custom Night",
        "TOK",
        "Counter-Strike 2",
        "Among Us",
        "TOK 2",
        "TOK HARDCORE",
        "Gravitas",
        "Hello Neighbor Alpha 1",
        "Hello Neighbor Alpha 2",
        "Hello Neighbor Alpha 3",
        "Anime Artist",
        "People Playground",
        "Apex Legends",
        "Mr. Hopp's Playhouse",
        "Discord Rich Me!",
        "Portal Reloaded",
        "Bhop PRO",
        "Kandidatos",
        "Hentai Girls - Anime Puzzle 18+",
        "Stumble Guys",
        "Anime Zodiac",
        "Dota 2"
      ]
    },
    {
      "username": "UC7W",
      "password": "mouse@mouse",
      "country": "US",
      "games": [
        "Grand Theft Auto V",
        "Aimlabs",
        "Call of Duty\\u00ae",
        "Combat Master",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "rfhu260971",
      "password": "Phamsangx2008",
      "country": "VN",
      "games": [
        "World of Warships",
        "Cube Racer",
        "Apex Legends",
        "eFootball\\u2122",
        "Dota 2",
        "Spacewar"
      ]
    },
    {
      "username": "sudalbankto1980",
      "password": "W1lmas11k..",
      "country": "AR",
      "games": [
        "Toribash",
        "Portal 2 Sixense Perceptual Pack",
        "Grimm",
        "Serena",
        "Counter-Strike 2",
        "Penumbra: Necrologue",
        "Blender",
        "The Desolate Hope",
        "Romance of the Three Kingdoms Maker",
        "Paladins",
        "Paladins - Public Test",
        "Tom Clancy's Ghost Recon Wildlands Open Beta",
        "The Descendant",
        "Drunken Wrestlers 2",
        "The Archotek Project",
        "AX:EL",
        "The Awesome Adventures of Captain Spirit",
        "Aimlabs",
        "Totally Accurate Battlegrounds",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "serhat1462",
      "password": "Ridvan123",
      "country": "ES",
      "games": [
        "Counter-Strike Nexon",
        "POSTAL",
        "Team Fortress 2"
      ]
    },
    {
      "username": "lp1nr9tj1mu8",
      "password": "Piotrek01!",
      "country": "CN",
      "games": [
        "Counter-Strike 2",
        "EA SPORTS FC\\u2122 25"
      ]
    },
    {
      "username": "IronShopWallpeper94631",
      "password": "IronShop034182",
      "country": "TH",
      "games": [
        "Brawlhalla",
        "Wallpaper Engine",
        "Apex Legends",
        "Strinova",
        "Totally Accurate Battlegrounds",
        "PUBG: BATTLEGROUNDS",
        "OBS Studio",
        "Call of Duty\\u00ae",
        "Delta Force",
        "Marvel Rivals",
        "Deceit 2",
        "BLOODSTRIKE",
        "Half-Life 2",
        "Half-Life 2: Deathmatch",
        "Half-Life Deathmatch: Source",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "gstm968",
      "password": "Yahia_2008",
      "country": "OM",
      "games": [
        "America's Army: Proving Grounds",
        "Warframe",
        "No More Room in Hell",
        "Counter-Strike Nexon",
        "Fishing Planet",
        "Brawlhalla",
        "World of Warships",
        "Yu-Gi-Oh! Duel Links",
        "SCP: Secret Laboratory",
        "Dead Frontier 2",
        "Ironsight",
        "Pixel Strike 3D",
        "Counter-Strike 2",
        "Stay Out",
        "Will To Live Online",
        "Slappyball",
        "Totally Accurate Battlegrounds",
        "eFootball\\u2122",
        "MultiVersus",
        "Stumble Guys",
        "MARVEL SNAP",
        "The Riflemen",
        "Roller Champions\\u2122",
        "Call of Duty\\u00ae",
        "Grapples Galore",
        "Combat Master",
        "StrangerZ",
        "1v1.LOL",
        "Scavenger",
        "Overwatch\\u00ae 2",
        "Sneak Out",
        "NARAKA: BLADEPOINT",
        "One-armed robber",
        "The Backrooms: Unbounded",
        "Supermarket Together",
        "Marvel Rivals",
        "ENDLESS\\u2122 Legend",
        "ONE PIECE Bounty Rush",
        "Dark Hours: Prologue",
        "The Backrooms Deluxe",
        "Half-Life 2",
        "Half-Life 2: Deathmatch",
        "Half-Life Deathmatch: Source",
        "Dark Sector",
        "Pankapu",
        "Spacewar"
      ]
    },
    {
      "username": "AmuckGreatHippopotamus",
      "password": "Badfact20",
      "country": "IE",
      "games": [
        "Brawlhalla",
        "Metin2",
        "Short Life",
        "Counter-Strike 2",
        "Team Fortress 2"
      ]
    },
    {
      "username": "Dy6Ao6Ue4Mo2",
      "password": "Nikosteamtekken1",
      "country": "RU",
      "games": [
        "Vampire: The Masquerade - Bloodhunt",
        "Counter-Strike 2",
        "PUBG: BATTLEGROUNDS",
        "TEKKEN 8",
        "TCG Card Shop Simulator: Prologue"
      ]
    },
    {
      "username": "lup2731",
      "password": "RedImba12345",
      "country": "PH",
      "games": [
        "Counter-Strike 2",
        "Dota Underlords",
        "Dota 2"
      ]
    },
    {
      "username": "jungseongbin",
      "password": "01051926268@",
      "country": "KR",
      "games": [
        "No More Room in Hell",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Don't Starve Together",
        "VRChat",
        "Black Squad",
        "Raft",
        "Deceit",
        "Russian Fishing 4",
        "Ironsight",
        "Aimlabs",
        "Destiny 2",
        "Apex Legends",
        "King of Crabs",
        "Paragon: The Overprime",
        "Bro Falls: Ultimate Showdown",
        "Goose Goose Duck",
        "Halo Infinite",
        "PUBG: BATTLEGROUNDS",
        "FPS Chess"
      ]
    },
    {
      "username": "sami0229",
      "password": "saminesl0145",
      "country": "TR",
      "games": [
        "The Witcher: Enhanced Edition",
        "The Witcher 2: Assassins of Kings Enhanced Edition",
        "Grand Theft Auto III",
        "Grand Theft Auto: Vice City",
        "Grand Theft Auto: San Andreas",
        "GRID 2",
        "The Forest",
        "Assetto Corsa",
        "7 Days to Die",
        "Borderlands: The Pre-Sequel",
        "A Story About My Uncle",
        "Metro 2033 Redux",
        "Half-Life 2: Update",
        "Deponia: The Complete Journey",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Dragon's Dogma: Dark Arisen",
        "Don't Starve Together",
        "Brawlhalla",
        "Business Tour - Online Multiplayer Board Game",
        "PUBG: BATTLEGROUNDS",
        "Raft",
        "Stick Fight: The Game",
        "Unturned",
        "Counter-Strike 2",
        "Among Us",
        "Yet Another Zombie Defense",
        "Ranch Simulator",
        "RISK: Global Domination",
        "Destiny 2",
        "A Way Out",
        "Mafia II (Classic)",
        "Mafia III: Definitive Edition",
        "Mafia II: Definitive Edition",
        "Mafia: Definitive Edition",
        "My Singing Monsters",
        "Gas Station Simulator: Prologue - Early Days",
        "Goose Goose Duck",
        "Muck",
        "eFootball\\u2122",
        "Viral Firar",
        "Asphalt Legends Unite",
        "Stumble Guys",
        "One-armed cook",
        "Trackmania",
        "Black Desert",
        "Delta Force",
        "One-armed robber",
        "Supermarket Together",
        "Supermarket Simulator: Prologue",
        "Content Warning",
        "ENDLESS\\u2122 Legend",
        "TCG Card Shop Simulator: Prologue",
        "BLOODSTRIKE",
        "Spacewar",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "johnknock",
      "password": "gaerwen",
      "country": "ID",
      "games": [
        "Counter-Strike",
        "Team Fortress Classic",
        "Day of Defeat",
        "Deathmatch Classic",
        "Half-Life: Opposing Force",
        "Ricochet",
        "Half-Life",
        "Half-Life: Blue Shift",
        "War Thunder",
        "Brawlhalla",
        "Mitos.is: The Game",
        "Business Tour - Online Multiplayer Board Game",
        "VRChat",
        "Metin2",
        "World of Tanks Blitz",
        "SCP: Secret Laboratory",
        "Deceit",
        "Zula Global",
        "HITMAN\\u2122 2",
        "Ultimate Custom Night",
        "Aimlabs",
        "Cube Racer",
        "Counter-Strike 2",
        "Quaver",
        "Project Torque",
        "RISK: Global Domination",
        "Destiny 2",
        "Apex Legends",
        "Krunker",
        "Gorilla Tag",
        "Torque Drift",
        "eFootball\\u2122",
        "PIGGY: Hunt",
        "The Two of Us",
        "PUBG: BATTLEGROUNDS",
        "Team Fortress 2"
      ]
    },
    {
      "username": "nveox866",
      "password": "oae578735D",
      "country": "HK",
      "games": [
        "Warframe",
        "War Thunder",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "understoodunequalchough",
      "password": "Crazygiraffe17",
      "country": "US",
      "games": [
        "LoveBeat",
        "Knight Online",
        "VRChat",
        "SCP: Secret Laboratory",
        "Counter-Strike 2",
        "Spacewar"
      ]
    },
    {
      "username": "hr6ko8etc5o3lipyti",
      "password": "GGDF20SQ6UQ9240",
      "country": "BR",
      "games": [
        "Counter-Strike 2",
        "Destiny 2",
        "Trove"
      ]
    },
    {
      "username": "depressedimpossiblemeerkat",
      "password": "Palehat33",
      "country": "US",
      "games": [
        "Fortress Forever",
        "Pirates",
        "Vikings",
        "&amp; Knights II",
        "Brawlhalla",
        "Knight Online",
        "Paladins",
        "Paladins - Public Test",
        "Metin2",
        "Drunken Wrestlers 2",
        "Unturned",
        "Splitgate",
        "BLOCKPOST LEGACY",
        "Battlerite Public Test",
        "Battlerite",
        "Counter-Strike 2",
        "Destiny 2",
        "Apex Legends",
        "COMBAT ARMS: THE CLASSIC",
        "STAR WARS\\u2122: The Old Republic\\u2122",
        "Children of Silentown: Prologue",
        "SuchArt: Creative Space",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "payod3",
      "password": "PayodM765",
      "country": "ZA",
      "games": [
        "Warframe",
        "Cry of Fear",
        "Robocraft",
        "Trove",
        "Warface: Clutch",
        "Paladins",
        "Paladins - Public Test",
        "Digimon Masters Online",
        "Unturned",
        "SCP: Secret Laboratory",
        "Deceit",
        "Ironsight",
        "Darwin Project",
        "Century: Age of Ashes",
        "Counter-Strike 2",
        "Destiny 2",
        "Apex Legends",
        "Stay Out",
        "Legends of Aria",
        "Shadow Arena",
        "COMBAT ARMS: THE CLASSIC",
        "Vectromirror 0",
        "Inertial Drift Sunset Prologue",
        "Dinosaur Fossil Hunter: Prologue",
        "MadGuns",
        "Dark Fracture: Prologue",
        "Krunker",
        "PRO DRIFT RELOADED"
      ]
    },
    {
      "username": "toby_isb",
      "password": "Toby1058",
      "country": "US",
      "games": [
        "Terraria",
        "Earth 2160",
        "Warframe",
        "Euro Truck Simulator",
        "Knights and Merchants",
        "World War II: Panzer Claws",
        "Subnautica",
        "Grand Theft Auto V",
        "Insurgency",
        "Warface: Clutch",
        "Skyrim Script Extender (SKSE)",
        "Firewatch",
        "The Witness",
        "Wallpaper Engine",
        "Tom Clancy's Rainbow Six Siege",
        "Tom Clancy's Rainbow Six Siege - Test Server",
        "The Witcher 3: Wild Hunt",
        "The Elder Scrolls V: Skyrim Special Edition",
        "Rocket League",
        "PUBG: BATTLEGROUNDS",
        "PC Building Simulator",
        "Jurassic World Evolution",
        "CS2D",
        "Splitgate",
        "Relik",
        "Fallout 4",
        "Getting Over It with Bennett Foddy",
        "War Trigger 2",
        "Aimtastic",
        "Ostalgie: The Berlin Wall",
        "Realm Royale Reforged",
        "Realm Royale - Test Server",
        "Aimlabs",
        "Counter-Strike 2",
        "Going Medieval",
        "Destiny 2",
        "Townscaper",
        "BISQUE DOLL",
        "Halo Infinite",
        "Team Fortress 2",
        "Dota 2",
        "Source SDK Base 2007",
        "Spacewar",
        "Sniper Elite 4 Dedicated Server",
        "Arma Reforger Server",
        "SteamVR",
        "Vox Machinae Dedicated Server"
      ]
    },
    {
      "username": "chlgustn06",
      "password": "asdf1848!!",
      "country": "KR",
      "games": [
        "Warframe",
        "Grand Theft Auto V",
        "Secret Neighbor",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "VenomousReminiscentOyster",
      "password": "Happyrhino93",
      "country": "IE",
      "games": [
        "Knight Online",
        "Metin2",
        "Counter-Strike 2",
        "Dota 2"
      ]
    },
    {
      "username": "x98_gs3u7S",
      "password": "3glKPq5i",
      "country": "LT",
      "games": [
        "Counter-Strike 2",
        "Destiny 2"
      ]
    },
    {
      "username": "roi123456a",
      "password": "Roi123456a1",
      "country": "CA",
      "games": [
        "America's Army: Proving Grounds",
        "Counter-Strike Nexon",
        "Dirty Bomb",
        "FreeStyle 2: Street Basketball",
        "Aftermath"
      ]
    },
    {
      "username": "MrTomas888",
      "password": "540161990m",
      "country": "US",
      "games": [
        "Robocraft",
        "Relic Hunters Zero: Remix",
        "Metin2",
        "Unturned",
        "Counter-Strike 2",
        "Apex Legends",
        "Dota 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "golenk15",
      "password": "oksaalmira",
      "country": "AR",
      "games": [
        "Grand Theft Auto III",
        "Grand Theft Auto: Vice City",
        "Grand Theft Auto: San Andreas",
        "Football Superstars",
        "Warframe",
        "Marvel Heroes Omega",
        "Happy Wars",
        "The Four Kings Casino and Slots",
        "Grand Theft Auto IV: The Complete Edition",
        "Robocraft",
        "Trove",
        "Unturned",
        "Warface: Clutch",
        "Heroes of SoulCraft",
        "Anno Online",
        "FreeStyle 2: Street Basketball",
        "RIFT",
        "SMITE",
        "SMITE - Public Test",
        "Knight Online",
        "Dungeon Defenders II",
        "Orcs Must Die! Unchained",
        "Governor of Poker 3",
        "Paladins",
        "Paladins - Public Test",
        "Pro Evolution Soccer 2016 myClub",
        "Crush Online",
        "Thanatos",
        "Destiny of Ancient Kingdoms\\u2122",
        "Atlas Reactor",
        "Zone4",
        "DC Universe Online",
        "Dota Underlords",
        "Bone Voyage",
        "Albion Online",
        "Dota 2",
        "Source Filmmaker",
        "Spacewar",
        "Source SDK Base 2007",
        "Assetto Corsa SDK",
        "Assetto Corsa Dedicated Server",
        "DayZ Server",
        "Call of Duty: Modern Warfare 3 - Dedicated Server",
        "7 Days to Die Dedicated Server",
        "Sniper Elite 4 Dedicated Server",
        "Half-Life Deathmatch: Source Dedicated server",
        "Team Fortress 2"
      ]
    },
    {
      "username": "yeider823",
      "password": "naruto823",
      "country": "UA",
      "games": [
        "Unturned",
        "SMITE",
        "SMITE - Public Test",
        "SCP: Secret Laboratory",
        "Deceit",
        "Counter-Strike 2",
        "Apex Legends",
        "PUBG: BATTLEGROUNDS",
        "Dota 2"
      ]
    },
    {
      "username": "Valen_8",
      "password": "energias4",
      "country": "IN",
      "games": [
        "Counter-Strike 2",
        "Destiny 2",
        "POSTAL"
      ]
    },
    {
      "username": "ExcellentMundaneGoldfish",
      "password": "Ivorywool44",
      "country": "IE",
      "games": [
        "Google Earth VR",
        "Brawlhalla",
        "Knight Online",
        "VRChat",
        "You Have 10 Seconds 2",
        "Metin2",
        "Deceit",
        "CRSED: Cuisine Royale",
        "Vegas Infinite by PokerStars",
        "Counter-Strike 2",
        "iVRy Driver for SteamVR",
        "Apex Legends",
        "Animaze",
        "Gorilla Tag",
        "eFootball\\u2122",
        "Crab Game",
        "Lost Ark",
        "Dota 2",
        "SteamVR"
      ]
    },
    {
      "username": "adjoiningwakefulcaterpillar",
      "password": "Ultraroad24",
      "country": "IE",
      "games": [
        "Knight Online",
        "Counter-Strike 2",
        "Team Fortress 2"
      ]
    },
    {
      "username": "g9l5aimso1rdwe9",
      "password": "IYQ3UCPPE718334",
      "country": "RU",
      "games": [
        "Deceit",
        "Counter-Strike 2"
      ]
    },
    {
      "username": "hv6uu0lg9uf5",
      "password": "Dakehermoso64",
      "country": "CN",
      "games": [
        "Counter-Strike 2",
        "Warhammer: Vermintide 2",
        "We Were Here Expeditions: The FriendShip",
        "Figment",
        "Tiny Tina's Assault on Dragon Keep: A Wonderlands One-shot Adventure",
        "Black Desert",
        "SLUDGE LIFE",
        "Battlestar Galactica Deadlock",
        "Desktop Dungeons",
        "Field of Glory II",
        "Metro: Last Light Complete Edition",
        "Warhammer 40",
        "000: Gladius - Relics of War",
        "TGV Voyages Train Simulator",
        "Hue",
        "Half-Life",
        "Train Simulator Classic 2024",
        "Dead Island Riptide Definitive Edition",
        "RPG Maker XP",
        "Space Crew: Legendary Edition",
        "100% Orange Juice",
        "Content Warning",
        "Machinika Museum",
        "ENDLESS\\u2122 Legend",
        "Islands of Insight",
        "Intravenous"
      ]
    },
    {
      "username": "umgh0t8d95o",
      "password": "jQpqs7qWm1",
      "country": "CN",
      "games": [
        "Counter-Strike 2"
      ]
    },
    {
      "username": "57woxixn",
      "password": "Hcy4117256818s",
      "country": "CN",
      "games": [
        "Portal",
        "Portal 2",
        "Tomb Raider",
        "Wallpaper Engine",
        "Rise of the Tomb Raider",
        "Counter-Strike 2",
        "Shadow of the Tomb Raider",
        "Radio Commander",
        "The Crew 2",
        "Kingdom Come: Deliverance",
        "Smart Game Booster",
        "DesktopMMD4:Born to Dance"
      ]
    },
    {
      "username": "jafialt7",
      "password": "BarterSahid123!",
      "country": "ID",
      "games": [
        "March of Empires",
        "Destiny 2"
      ]
    },
    {
      "username": "samakaiyoyo",
      "password": "peak2917",
      "country": "TH",
      "games": [
        "Path of Exile",
        "Syberia 3",
        "Destiny 2",
        "Syberia The World Before - Prologue",
        "Undecember",
        "Path of Exile 2"
      ]
    },
    {
      "username": "embarrassedgoldfish1774",
      "password": "e4f01ac0c66edf121!aZ",
      "country": "FR",
      "games": [
        "Stationeers"
      ]
    },
    {
      "username": "qomst53326",
      "password": "UQ1800033",
      "country": "CN",
      "games": [
        "KARDS - The WWII Card Game",
        "Counter-Strike 2"
      ]
    },
    {
      "username": "wedvtdastou",
      "password": "S3tjDZONibsNFg7",
      "country": "PK",
      "games": [
        "Counter-Strike 2",
        "Captain of Industry",
        "Team Fortress 2",
        "Unturned"
      ]
    },
    {
      "username": "karlychan1",
      "password": "MhdAbdullah2131",
      "country": "ID",
      "games": [
        "Business Tour - Online Multiplayer Board Game",
        "Black Squad",
        "Vampire: The Masquerade - Bloodhunt",
        "Counter-Strike 2",
        "Dota Underlords",
        "Apex Legends",
        "Bro Falls: Ultimate Showdown",
        "Stumble Guys",
        "Combat Master"
      ]
    },
    {
      "username": "Sales454",
      "password": "05376924225b",
      "country": "TR",
      "games": [
        "Garry's Mod",
        "Left 4 Dead 2",
        "Driver San Francisco",
        "Euro Truck Simulator 2",
        "War Thunder",
        "The Forest",
        "PAYDAY 2",
        "Spintires\\u00ae",
        "BeamNG.drive",
        "S.K.I.L.L. - Special Force 2",
        "Unturned",
        "Heroes &amp; Generals",
        "Car Mechanic Simulator 2015",
        "Counter-Strike 2",
        "Transformice",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Resident Evil Revelations 2",
        "SURVIVAL: Postapocalypse Now",
        "Brawlhalla",
        "Scrap Mechanic",
        "Tower Unite",
        "Business Tour - Online Multiplayer Board Game",
        "Heaven Island - VR MMO",
        "Creativerse",
        "Who's Your Daddy?!",
        "Wallpaper Engine",
        "VRChat",
        "Paladins",
        "Paladins - Public Test",
        "Black Squad",
        "Of Guards And Thieves",
        "Friday the 13th: The Game",
        "TERA",
        "Ratty Catty",
        "CarX Drift Racing Online",
        "Hand Simulator",
        "Zula T\\u00fcrkiye",
        "Soundpad",
        "Phasmophobia",
        "Ring of Elysium",
        "Paunch",
        "THE DAY Online",
        "Realm Royale Reforged",
        "Realm Royale - Test Server",
        "Z1 Battle Royale",
        "H1Z1: Test Server",
        "Pummel Party",
        "Aimlabs",
        "Conqueror's Blade",
        "Game Migrated to Another Steam Page",
        "CombatArms: Reloaded",
        "Hand Simulator: Survival",
        "Among Us",
        "Pacify",
        "Hide and Seek",
        "Fall Guys",
        "Gang Beasts",
        "Apex Legends",
        "Sea of Thieves",
        "RUSSIAPHOBIA",
        "Grand Theft Auto IV: The Complete Edition",
        "DEVOUR",
        "Agrou",
        "In Silence",
        "Contraband Police: Prologue",
        "Krunker",
        "Drive 21",
        "Feign",
        "Bakery Magnate: Beginning",
        "I Am Fish",
        "Crab Game",
        "SCP: Containment Breach Multiplayer",
        "Call of Duty\\u00ae: Modern Warfare\\u00ae II - Open Beta",
        "Team Fortress 2"
      ]
    },
    {
      "username": "nngochuy032",
      "password": "huy03022005",
      "country": "VN",
      "games": [
        "Warframe",
        "War Thunder",
        "DCS World Steam Edition",
        "theHunter Classic",
        "World of Warships",
        "Vampire: The Masquerade - Bloodhunt",
        "Aimlabs",
        "Counter-Strike 2",
        "Destiny 2",
        "Apex Legends",
        "Stay Out",
        "STAR WARS\\u2122: The Old Republic\\u2122",
        "Old School RuneScape",
        "Badlanders",
        "Goose Goose Duck",
        "Muck",
        "Pirates",
        "Halo Infinite",
        "SCP: Containment Breach Multiplayer",
        "PUBG: BATTLEGROUNDS",
        "Poppy Playtime",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Warhaven",
        "NARAKA: BLADEPOINT"
      ]
    },
    {
      "username": "meliodass544",
      "password": "Ka112233",
      "country": "AR",
      "games": [
        "PAYDAY 2",
        "SCUM",
        "Onmyoji",
        "Malum",
        "Fear Therapy",
        "Dota 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "fronglnw157",
      "password": "0846540303",
      "country": "TH",
      "games": [
        "Warframe",
        "Grand Theft Auto V",
        "FreeStyle 2: Street Basketball",
        "Deceit",
        "Far Cry 5",
        "KurtzPel",
        "Aimlabs",
        "Counter-Strike 2",
        "Royal Crown",
        "Apex Legends",
        "Conqueror's Blade",
        "Dota 2",
        "Source SDK Base 2007",
        "Assetto Corsa SDK",
        "Half-Life Deathmatch: Source Dedicated server",
        "Spacewar",
        "Call of Duty: Modern Warfare 3 - Dedicated Server"
      ]
    },
    {
      "username": "Shetty_Bro21",
      "password": "Sudeepjs#1",
      "country": "IN",
      "games": [
        "EVE Online",
        "Tank Force: Online Shooter Game",
        "War Robots",
        "Ironsight",
        "Modern Combat 5",
        "Counter-Strike 2",
        "Apex Legends",
        "Lost Light",
        "PUBG: BATTLEGROUNDS",
        "Farlight 84",
        "Call of Duty\\u00ae",
        "Combat Master"
      ]
    },
    {
      "username": "qd5ic2or9ob7",
      "password": "yassinsassi0000009999&@@",
      "country": "UY",
      "games": [
        "Grand Theft Auto V"
      ]
    },
    {
      "username": "amanda29leoni",
      "password": "7HX5UP9EKE4622",
      "country": "RS",
      "games": [
        "Counter-Strike 2",
        "Destiny 2"
      ]
    },
    {
      "username": "love0915417313",
      "password": "love0928411209",
      "country": "TW",
      "games": [
        "Conan Exiles",
        "Conan Exiles - Public Beta Client",
        "Counter-Strike 2",
        "SYNCED",
        "Destiny 2",
        "I Wanna Maker",
        "Bloons TD Battles 2",
        "Conqueror's Blade",
        "\\u96c0\\u9b42\\u9ebb\\u5c06(MahjongSoul)",
        "Undecember",
        "MIR4",
        "Tell Me Why",
        "RunnerDot",
        "Titan Quest Anniversary Edition",
        "Jagged Alliance Gold",
        "PUBG: BATTLEGROUNDS",
        "VPet-Simulator",
        "Minion Masters",
        "THE FINALS",
        "Warhammer: Vermintide 2",
        "Call of Duty\\u00ae",
        "We Were Here Expeditions: The FriendShip",
        "Overwatch\\u00ae 2",
        "Their Land",
        "Metro: Last Light Complete Edition",
        "NARAKA: BLADEPOINT",
        "Age of Empires III: Definitive Edition",
        "Astral Party",
        "Nut City Blues",
        "Space Crew: Legendary Edition",
        "Monstrum 2",
        "100% Orange Juice",
        "ENDLESS\\u2122 Legend",
        "Game Of Thrallan",
        "East Trade Tycoon: Inheritance",
        "BROKE PROTOCOL",
        "NO STRANGERS",
        "Half-Life 2",
        "Half-Life 2: Deathmatch",
        "Half-Life Deathmatch: Source",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "jerry2k62",
      "password": "30112006Nam",
      "country": "US",
      "games": [
        "PUBG: BATTLEGROUNDS",
        "CounterSide"
      ]
    },
    {
      "username": "Vipfum",
      "password": "teofil2002",
      "country": "RO",
      "games": [
        "Homefront",
        "Euro Truck Simulator 2",
        "World War II: Panzer Claws",
        "Amnesia: The Dark Descent",
        "Amnesia: A Machine for Pigs",
        "DiRT 3 Complete Edition",
        "Counter-Strike 2",
        "PC Building Simulator",
        "Unturned",
        "Battlegun",
        "Piggy Poggy Pog",
        "Kingdom: Classic",
        "Secret Neighbor Beta",
        "Team Fortress 2"
      ]
    },
    {
      "username": "21dghtdwef84",
      "password": "SG088ZQ734",
      "country": "AR",
      "games": [
        "Pinball FX3",
        "MONMUSU",
        "Ultimate Custom Night",
        "Welcome to Free Will",
        "PUBG: BATTLEGROUNDS",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest"
      ]
    },
    {
      "username": "lciml93187",
      "password": "YZ2504385",
      "country": "CN",
      "games": [
        "Counter-Strike 2"
      ]
    },
    {
      "username": "z405290346",
      "password": "y987662115",
      "country": "US",
      "games": [
        "Counter-Strike 2"
      ]
    },
    {
      "username": "Stray_stt",
      "password": "STRAY@9836",
      "country": "SA",
      "games": [
        "War Thunder",
        "DCS World Steam Edition",
        "Caliber",
        "Dark Deception",
        "how do you Do It?",
        "Brawlhalla",
        "DDNet",
        "Rec Room",
        "Life is Strange\\u2122",
        "Resident Evil 7 Teaser: Beginning Hour",
        "We Were Here",
        "Fallout Shelter",
        "Drunken Wrestlers 2",
        "Real Pool 3D - Poolians",
        "ScreenPlay",
        "Splitgate",
        "SCP: Secret Laboratory",
        "Deceit",
        "Aimlabs",
        "Counter-Strike 2",
        "Cell to Singularity - Evolution Never Ends",
        "Hello Neighbor Alpha 1",
        "Destiny 2",
        "Apex Legends",
        "VTube Studio",
        "Stray",
        "Contraband Police: Prologue",
        "Mr.Mine",
        "Krunker",
        "Yu-Gi-Oh!  Master Duel",
        "Gas Station Simulator: Prologue - Early Days",
        "3D Aim Trainer",
        "Muck",
        "College Bound",
        "eFootball\\u2122",
        "Electrician Simulator - First Shock",
        "Crab Game",
        "MultiVersus",
        "PUBG: BATTLEGROUNDS",
        "OBS Studio",
        "Farlight 84",
        "Stumble Guys",
        "One-armed cook",
        "Poppy Playtime",
        "Wallpaper Alive",
        "FPS Chess",
        "THE FINALS",
        "The First Descendant",
        "Once Human",
        "Call of Duty\\u00ae",
        "Thief Simulator 2: Prologue",
        "Combat Master",
        "StrangerZ",
        "1v1.LOL",
        "Sky: Children of the Light",
        "Overwatch\\u00ae 2",
        "HoloCure - Save the Fans!",
        "Delta Force",
        "NARAKA: BLADEPOINT",
        "Crime Scene Cleaner: Prologue",
        "One-armed robber",
        "Chained Together",
        "Spectre Divide",
        "NIGHT-RUNNERS PROLOGUE",
        "Supermarket Together",
        "Supermarket Simulator: Prologue",
        "Lust Goddess",
        "Rent A Car Simulator 24: Prologue",
        "Banana",
        "Rally Mechanic Simulator Prologue",
        "It Takes Two",
        "Dark and Darker",
        "Retail Company Simulator: Prologue",
        "TCG Card Shop Simulator: Prologue",
        "Kaf village",
        "BLOODSTRIKE",
        "Vigor",
        "Spacewar",
        "Source SDK Base 2007",
        "Aeons Echo",
        "Sex Coach: Hot Yoga - Prologue",
        "My Sexy Neighbor \\ud83d\\udd1e Prologue",
        "Drive Beyond Horizons Demo",
        "Call of Duty: Modern Warfare 3 - Dedicated Server",
        "SteamVR",
        "7 Days to Die Dedicated Server",
        "HITMAN 3 Free Starter Pack"
      ]
    },
    {
      "username": "nherzw2332",
      "password": "GPthuhq42E",
      "country": "US",
      "games": [
        "Counter-Strike 2"
      ]
    },
    {
      "username": "shadowstrom29",
      "password": "HiLow111",
      "country": "IN",
      "games": [
        "Aimlabs",
        "Destiny 2",
        "Apex Legends",
        "Battlefield 1 \\u2122",
        "Battlefield 4\\u2122",
        "Battlefield\\u2122 V",
        "Dota 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "Zonkierombie",
      "password": "741596328Zetsu",
      "country": "BE",
      "games": [
        "Brawlhalla",
        "Wallpaper Engine",
        "DARK SOULS\\u2122 III",
        "The Cycle: Frontier",
        "Monster Hunter: World",
        "Counter-Strike 2",
        "EA SPORTS\\u2122 FIFA 21",
        "Spellbreak",
        "PUBG: BATTLEGROUNDS",
        "KEO",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Call of Duty\\u00ae",
        "Spacewar"
      ]
    },
    {
      "username": "p486690740",
      "password": "t762876293",
      "country": "CN",
      "games": [
        "Counter-Strike 2"
      ]
    },
    {
      "username": "andy03127",
      "password": "Aa970312071586",
      "country": "CN",
      "games": [
        "Top Burger"
      ]
    },
    {
      "username": "usaman651",
      "password": "Ayyanprince0",
      "country": "PK",
      "games": [
        "Destiny 2",
        "Banana"
      ]
    },
    {
      "username": "kentty03",
      "password": "040806Anh",
      "country": "VN",
      "games": [
        "Cube Racer",
        "Counter-Strike 2",
        "Apex Legends",
        "Goose Goose Duck",
        "PUBG: BATTLEGROUNDS",
        "Call of Duty\\u00ae",
        "NARAKA: BLADEPOINT"
      ]
    },
    {
      "username": "KatsuyaNatsuo",
      "password": "MeliodasTristan",
      "country": "BR",
      "games": [
        "Deceit",
        "Apex Legends",
        "Stay Out",
        "Will To Live Online",
        "Badlanders",
        "Zombie Carnage 2",
        "Lost Light",
        "Stumble Guys",
        "NARAKA: BLADEPOINT"
      ]
    },
    {
      "username": "sharouski",
      "password": "Sasha45908",
      "country": "BY",
      "games": [
        "Race: The WTCC Game",
        "Call of Duty\\u00ae: Modern Warfare\\u00ae 3 (2011)",
        "Call of Duty\\u00ae: Modern Warfare\\u00ae 3 (2011) - Multiplayer",
        "War Thunder",
        "Panzar",
        "Counter-Strike Nexon",
        "S.K.I.L.L. - Special Force 2",
        "Robocraft",
        "BLOCKADE 3D",
        "Trove",
        "Heroes &amp; Generals",
        "Dead Island: Epidemic",
        "Brick-Force",
        "Counter-Strike 2",
        "Apex Legends",
        "eFootball PES 2021 SEASON UPDATE"
      ]
    },
    {
      "username": "rywyo10740",
      "password": "PJ7122632",
      "country": "CN",
      "games": [
        "Counter-Strike 2"
      ]
    },
    {
      "username": "liuguijun123",
      "password": "XfuVXqqeyR",
      "country": "CN",
      "games": [
        "Warframe",
        "Warface: Clutch",
        "SMITE",
        "SMITE - Public Test",
        "Brawlhalla",
        "Wallpaper Engine",
        "World of Warships",
        "PUBG: BATTLEGROUNDS",
        "Counter-Strike 2",
        "War Robots",
        "The Cycle: Frontier",
        "DEAD OR ALIVE Xtreme Venus Vacation",
        "Destiny 2",
        "Apex Legends",
        "Battlefield 1 \\u2122",
        "Bless Unleashed",
        "Conqueror's Blade",
        "World of Tanks",
        "Battlefield\\u2122 V",
        "Soul Dossier",
        "R2Beat: \\u97f3\\u901f\\u89c9\\u9192",
        "Zombie Carnage 2",
        "PICO PARK:Classic Edition",
        "\\u6b7b\\u5bc2\\uff08DeathlyStillness\\uff09",
        "Halo Infinite",
        "Beholder",
        "KEO",
        "\\u8fdf\\u5230\\u6444\\u5f71\\u5e08 Late photographer",
        "Call of Juarez Gunslinger",
        "Minion Masters",
        "Knightfall: A Daring Journey",
        "Bomber Crew",
        "Capcom Arcade Stadium",
        "Ninja Stealth",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Dota 2",
        "Source SDK Base 2007",
        "Spacewar",
        "Sniper Elite 4 Dedicated Server"
      ]
    },
    {
      "username": "whdhkmg3",
      "password": "DD0808769",
      "country": "AR",
      "games": [
        "Raft",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "jafialt8",
      "password": "BarterSahid123!",
      "country": "ID",
      "games": [
        "March of Empires",
        "Destiny 2"
      ]
    },
    {
      "username": "ddnjk35895",
      "password": "165thnt156ej1560",
      "country": "UY",
      "games": [
        "Grand Theft Auto V",
        "Counter-Strike 2"
      ]
    },
    {
      "username": "yoshuar4",
      "password": "Lolkun12",
      "country": "MX",
      "games": [
        "VRChat",
        "Apex Legends"
      ]
    },
    {
      "username": "agt9080",
      "password": "Dc2843943",
      "country": "CN",
      "games": [
        "PlanetSide 2",
        "PlanetSide 2 - Test",
        "Warframe",
        "War Thunder",
        "DCS World Steam Edition",
        "Arma 3",
        "Caliber",
        "Warface: Clutch",
        "Heroes &amp; Generals",
        "Dark Deception",
        "Fishing Planet",
        "SMITE",
        "SMITE - Public Test",
        "Governor of Poker 3",
        "VRChat",
        "Life is Strange\\u2122",
        "KARDS - The WWII Card Game",
        "World of Warships",
        "World of Tanks Blitz",
        "Alien Swarm: Reactive Drop",
        "Real Pool 3D - Poolians",
        "ScreenPlay",
        "NAVYFIELD",
        "Unturned",
        "SCP: Secret Laboratory",
        "Counter-Strike 2",
        "Operation: Harsh Doorstop",
        "Golden Hornet",
        "Vampire: The Masquerade - Bloodhunt",
        "Russian Fishing 4",
        "War Robots",
        "Dreadnought",
        "HITMAN\\u2122 2",
        "The Cycle: Frontier",
        "Ultimate Custom Night",
        "Rogue Company",
        "Pool 2D - Poolians",
        "Aimlabs",
        "Modern Combat 5",
        "DYNASTY WARRIORS 9",
        "Lords Mobile",
        "Hello Neighbor Alpha 1",
        "Lurk in the Dark : Prologue",
        "UNDEFEATED",
        "RetroArch",
        "Second Galaxy",
        "Hired Ops",
        "Destiny 2",
        "Apex Legends",
        "Resident Evil 2 \\",
        "King of Crabs",
        "Smart Game Booster",
        "Redmatch 2",
        "Train Station Renovation - First Job",
        "Conqueror's Blade",
        "POLYGON",
        "Helltaker",
        "Occupy Mars: Prologue",
        "\\u96c0\\u9b42\\u9ebb\\u5c06(MahjongSoul)",
        "\\u50cf\\u7d20\\u5973\\u53cb",
        "Contraband Police: Prologue",
        "Republic of Jungle",
        "Prison Simulator: Prologue",
        "World of Tanks",
        "\\u5c0f\\u9ed1\\u76d2\\u52a0\\u901f\\u5668",
        "A.V.A Global",
        "Super Animal Royale",
        "Aircraft Carrier Survival: Prolouge",
        "My boss is weird",
        "Word Game: Episode 0",
        "Totally Accurate Battlegrounds",
        "NEKOPARA - Catboys Paradise",
        "Zombie Gunship Survival",
        "Goose Goose Duck",
        "Muck",
        "XERA: Survival",
        "\\u679d\\u6c5f\\u5f80\\u4e8b",
        "Ship Graveyard Simulator: Prologue",
        "Fears to Fathom - Episode 1",
        "\\u6b7b\\u5bc2\\uff08DeathlyStillness\\uff09",
        "Halo Infinite",
        "SCP: Containment Breach Multiplayer",
        "Lost Light",
        "Classified Stories: Color Out of Space",
        "Ghostwire: Tokyo - Prelude",
        "PUBG: BATTLEGROUNDS",
        "OBS Studio",
        "VPet-Simulator",
        "DogeFight",
        "Battle Teams 2",
        "Poppy Playtime",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "THE FINALS",
        "World War 3",
        "The Sims\\u2122 4",
        "Call of Duty\\u00ae",
        "Trans-Siberian Railway Simulator: Prologue",
        "Thief Simulator 2: Prologue",
        "Combat Master",
        "Drift Experience Japan",
        "Coral Caper",
        "NARAKA: BLADEPOINT",
        "Aviators",
        "Intravenous 2: Mercenarism",
        "Arma 3 Tools",
        "Source SDK Base 2007",
        "Half-Life",
        "It Takes Two Friend's Pass"
      ]
    },
    {
      "username": "jafialt6",
      "password": "BarterSahid123!",
      "country": "ID",
      "games": [
        "War Thunder",
        "DCS World Steam Edition",
        "WWII Online",
        "War Trigger 3",
        "Caliber",
        "Warface: Clutch",
        "Armored Warfare",
        "Black Squad",
        "World of Tanks Blitz",
        "March of Empires",
        "Company of Heroes: Battle of Crete",
        "Operation: Harsh Doorstop",
        "Battle Tanks: World War II",
        "Ironsight",
        "CRSED: Cuisine Royale",
        "Phantasy Star Online 2 New Genesis",
        "Destiny 2",
        "Apex Legends",
        "COMBAT ARMS: THE CLASSIC",
        "Redmatch 2",
        "World of Tanks",
        "A.V.A Global",
        "Open Mod",
        "MY HERO ULTRA RUMBLE",
        "Lost Light",
        "PUBG: BATTLEGROUNDS",
        "Farlight 84",
        "The Riflemen",
        "THE FINALS",
        "The First Descendant",
        "Havoc",
        "World War 3",
        "Combat Master",
        "1v1.LOL",
        "Overwatch\\u00ae 2",
        "Project Hardline",
        "Their Land",
        "Pixel Gun 3D: PC Edition",
        "Frontline 1942: Battles of the World War 2",
        "Spectre Divide",
        "Palia",
        "Battle Teams 2",
        "Enlisted",
        "Vigor"
      ]
    },
    {
      "username": "HollowCynicalMeerkat",
      "password": "Bumpyface47",
      "country": "US",
      "games": [
        "Knight Online",
        "Metin2",
        "Counter-Strike 2",
        "Lost Ark",
        "Dota 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "lvidolin",
      "password": "75374120aA",
      "country": "RU",
      "games": [
        "America's Army: Proving Grounds",
        "War Thunder",
        "Tom Clancy's Ghost Recon Phantoms - NA",
        "Age of Conan: Unchained",
        "Grand Theft Auto V",
        "Warface: Clutch",
        "Heroes &amp; Generals",
        "Skyrim Script Extender (SKSE)",
        "Just Cause 3",
        "Paladins",
        "Paladins - Public Test",
        "Argo",
        "Splitgate",
        "Ring of Elysium",
        "Enderal: Forgotten Stories",
        "Counter-Strike 2",
        "Destiny 2",
        "Barro 2020",
        "Apex Legends",
        "Stay Out",
        "Syberia",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "coltimus123",
      "password": "clientes22",
      "country": "BR",
      "games": [
        "Fishing Planet",
        "Brawlhalla",
        "Yu-Gi-Oh! Duel Links",
        "Driver Booster for Steam",
        "Counter-Strike 2",
        "Destiny 2",
        "Marbles on Stream",
        "Apex Legends",
        "STAR WARS\\u2122: The Old Republic\\u2122",
        "Yu-Gi-Oh!  Master Duel",
        "eFootball PES 2021 SEASON UPDATE",
        "eFootball\\u2122",
        "PUBG: BATTLEGROUNDS",
        "Stumble Guys",
        "MARVEL SNAP",
        "Once Human",
        "Call of Duty\\u00ae",
        "Garten of Banban",
        "Delta Force",
        "Marvel Rivals",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "ugiugi1231",
      "password": "BB5banka_",
      "country": "LV",
      "games": [
        "Batman: Arkham City GOTY",
        "TrackMania Nations Forever",
        "Loadout",
        "PlanetSide 2",
        "PlanetSide 2 - Test",
        "Path of Exile",
        "No More Room in Hell",
        "Trove",
        "Counter-Strike 2",
        "Dirty Bomb",
        "Ghost in the Shell: Stand Alone Complex - First Assault Online",
        "Piercing Blow",
        "SMITE",
        "SMITE - Public Test",
        "Business Tour - Online Multiplayer Board Game",
        "Block N Load",
        "Paladins",
        "Paladins - Public Test",
        "Argo",
        "Black Squad",
        "Crossout",
        "Einar",
        "Unturned",
        "Secret World Legends",
        "Ring of Elysium",
        "Friday the 13th: Killer Puzzle",
        "Tom Clancy's Rainbow Six Siege",
        "Tom Clancy's Rainbow Six Siege - Test Server",
        "Realm Royale Reforged",
        "Realm Royale - Test Server",
        "Team Fortress 2"
      ]
    },
    {
      "username": "MattHDPoland",
      "password": "M@ttimsf18",
      "country": "PL",
      "games": [
        "Saints Row 2",
        "Homefront",
        "Borderlands GOTY",
        "Borderlands GOTY Enhanced",
        "Saints Row: The Third",
        "GRID",
        "Borderlands 2",
        "Marvel Puzzle Quest",
        "theHunter Classic",
        "Euro Truck Simulator 2",
        "F1 2015",
        "Car Mechanic Simulator 2015",
        "DiRT 3 Complete Edition",
        "Saints Row: Gat out of Hell",
        "Clicker Heroes",
        "Risen 3 - Titan Lords",
        "Gothic Playable Teaser",
        "Business Tour - Online Multiplayer Board Game",
        "Pro Evolution Soccer 2016 myClub",
        "American Truck Simulator",
        "Paladins",
        "Paladins - Public Test",
        "Sniper Fury",
        "Borderlands: The Pre-Sequel",
        "Ring of Elysium",
        "Counter-Strike 2",
        "Lethal Company"
      ]
    },
    {
      "username": "emircaaanw12",
      "password": "emircanss12",
      "country": "TR",
      "games": [
        "Real Pool 3D - Poolians",
        "Zula T\\u00fcrkiye",
        "Aimlabs",
        "Counter-Strike 2",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "jafialt5",
      "password": "BarterSahid123",
      "country": "ID",
      "games": [
        "March of Empires",
        "eFootball\\u2122",
        "PICO PARK:Classic Edition"
      ]
    },
    {
      "username": "IncredibleCrazyCrocodile",
      "password": "Greenolive68",
      "country": "US",
      "games": [
        "Counter-Strike 2",
        "Apex Legends",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "rvmaf081",
      "password": "bgg4199PP",
      "country": "AR",
      "games": [
        "VRChat",
        "TOXIKK",
        "Counter-Strike 2",
        "Night of the Full Moon",
        "BirdGut",
        "Riddle Joker",
        "Undecember",
        "Goose Goose Duck",
        "eFootball\\u2122",
        "PUBG: BATTLEGROUNDS",
        "OBS Studio",
        "Limbus Company",
        "Hero's Land",
        "Overwatch\\u00ae 2"
      ]
    },
    {
      "username": "Carequildo",
      "password": "@4256Noth",
      "country": "BR",
      "games": [
        "Counter-Strike 2",
        "GrandChase",
        "Destiny 2",
        "Halo Infinite",
        "THRONE AND LIBERTY",
        "Delta Force",
        "Once Human"
      ]
    },
    {
      "username": "ahmetfurkanerbaserbas",
      "password": "furkan99A",
      "country": "DE",
      "games": [
        "Far Cry",
        "Plants vs. Zombies: Game of the Year",
        "Far Cry\\u00ae 3",
        "Borderlands GOTY",
        "Borderlands GOTY Enhanced",
        "Witch's Pranks: Frog's Fortune Collector's Edition",
        "Hard West",
        "Blood and Bacon",
        "Summer Sale",
        "Neon Hardcore",
        "Zula T\\u00fcrkiye",
        "Zula Global",
        "HITMAN\\u2122 2",
        "HellCat",
        "Detective Story",
        "ZombieVan Drive",
        "Team Fortress 2",
        "Dota 2",
        "Alien Swarm",
        "Unreal Development Kit",
        "Empires",
        "Estranged: Act I"
      ]
    },
    {
      "username": "befoyh",
      "password": "Sacha4ever*",
      "country": "FR",
      "games": [
        "Warframe",
        "War Thunder",
        "Mount &amp; Blade II: Bannerlord",
        "Fishing Planet",
        "Fallout Shelter",
        "Yu-Gi-Oh! Duel Links",
        "FINAL FANTASY XV WINDOWS EDITION",
        "Conqueror's Blade",
        "Game Migrated to Another Steam Page",
        "Total War: THREE KINGDOMS",
        "World of Tanks",
        "Yu-Gi-Oh!  Master Duel",
        "Kingdom: Classic",
        "Hogwarts Legacy",
        "Lust Goddess",
        "Aeons Echo",
        "FINAL FANTASY XV WINDOWS EDITION PLAYABLE DEMO"
      ]
    },
    {
      "username": "kzrg85688",
      "password": "Km3Aj1Rj4Ki96t",
      "country": "IN",
      "games": [
        "RaceRoom Racing Experience",
        "Counter-Strike 2",
        "Torque Drift",
        "Stumble Guys",
        "Wallpaper Alive",
        "EA SPORTS FC\\u2122 24",
        "Banana",
        "Rally Mechanic Simulator Prologue",
        "Euro Truck Simulator 2 Demo"
      ]
    },
    {
      "username": "vipfum",
      "password": "teofil2002",
      "country": "RO",
      "games": [
        "Homefront",
        "Euro Truck Simulator 2",
        "World War II: Panzer Claws",
        "Amnesia: The Dark Descent",
        "Amnesia: A Machine for Pigs",
        "DiRT 3 Complete Edition",
        "Counter-Strike 2",
        "PC Building Simulator",
        "Unturned",
        "Battlegun",
        "Piggy Poggy Pog",
        "Kingdom: Classic",
        "Secret Neighbor Beta",
        "Team Fortress 2"
      ]
    },
    {
      "username": "vijfyd9148",
      "password": "CTdideh87N",
      "country": "TR",
      "games": [
        "Counter-Strike 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "Tiscic5",
      "password": "dPLjmNsZzb27BdX5",
      "country": "IN",
      "games": [
        "Call of Duty 4: Modern Warfare (2007)",
        "Arma 3",
        "Call of Duty: Advanced Warfare",
        "Call of Duty: Advanced Warfare - Multiplayer",
        "Apex Legends",
        "Medal of Honor\\u2122: Above and Beyond",
        "Aircraft Carrier Survival: Prolouge",
        "PUBG: BATTLEGROUNDS"
      ]
    },
    {
      "username": "rayanegaming2007",
      "password": "Rayane31",
      "country": "DZ",
      "games": [
        "Warframe",
        "DCS World Steam Edition",
        "Counter-Strike Nexon",
        "Dirty Bomb",
        "Brawlhalla",
        "Project CARS - Pagani Edition",
        "Black Squad",
        "EVE Online",
        "Totemori",
        "Soldat",
        "CS2D",
        "Zombie Panic! Source",
        "Darwin Project",
        "Aimlabs",
        "Counter-Strike 2",
        "CreativeDestruction",
        "Soccer Manager 2020",
        "WGT Golf",
        "Team Fortress 2"
      ]
    },
    {
      "username": "Totalwarphardehlbrt02",
      "password": "LCROBMERr02",
      "country": "VN",
      "games": [
        "MechWarrior Online",
        "Ancestors Legacy",
        "Far Cry 5",
        "Counter-Strike 2",
        "Baldi's Basics Classic Remastered",
        "PUBG: BATTLEGROUNDS",
        "Warhammer 40",
        "000: Warpforge",
        "Hot Therapy",
        "Total War: PHARAOH",
        "Total War: PHARAOH DYNASTIES",
        "Age of Empires III: Definitive Edition",
        "Dota 2",
        "Total War: THREE KINGDOMS",
        "Company of Heroes 3: Mission Alpha",
        "Company of Heroes 2"
      ]
    },
    {
      "username": "swcangyi",
      "password": "Sw566875",
      "country": "CN",
      "games": [
        "Warframe",
        "Eternal Senia",
        "SMITE",
        "SMITE - Public Test",
        "Brawlhalla",
        "Crush Crush",
        "Life is Strange\\u2122",
        "SCP: Secret Laboratory",
        "Counter-Strike 2",
        "Russian Fishing 4",
        "Aimlabs",
        "Mojo 2: Mia",
        "DEAD OR ALIVE Xtreme Venus Vacation",
        "Firestone: Online Idle RPG",
        "Eternal Return",
        "There is No GreenDam",
        "Destiny 2",
        "Apex Legends",
        "War of the Three Kingdoms",
        "Haiku",
        "the Robot",
        "Strinova",
        "\\u96c0\\u9b42\\u9ebb\\u5c06(MahjongSoul)",
        "Angel Legion: LSP Idle RPG",
        "Action Taimanin",
        "Soulworker",
        "\\u5c0f\\u9ed1\\u76d2\\u52a0\\u901f\\u5668",
        "Bro Falls: Ultimate Showdown",
        "Goose Goose Duck",
        "Monster Hunter Rise: Sunbreak Demo",
        "PUBG: BATTLEGROUNDS",
        "OBS Studio",
        "VPet-Simulator",
        "Farlight 84",
        "Stumble Guys",
        "Battle Teams 2",
        "Limbus Company",
        "THE FINALS",
        "The First Descendant",
        "Soulstone Survivors: Prologue",
        "Once Human",
        "Call of Duty\\u00ae",
        "BlazBlue Entropy Effect",
        "Hero's Land",
        "Arrow a Row",
        "NARAKA: BLADEPOINT",
        "Sword of Convallaria",
        "Crime Scene Cleaner: Prologue",
        "Astral Party",
        "Deceit 2",
        "Dark and Darker",
        "East Trade Tycoon: Inheritance",
        "Shape of Dreams: Prologue",
        "\\u9b3c\\u8c37\\u516b\\u8352 Tale of Immortal",
        "Spacewar",
        "Soundpad Demo"
      ]
    },
    {
      "username": "Emqu0808",
      "password": "IhA8erulFb",
      "country": "US",
      "games": [
        "Grand Theft Auto V",
        "Blasphemous"
      ]
    },
    {
      "username": "wirrr00340",
      "password": "Now123456789",
      "country": "AR",
      "games": [
        "Terraria",
        "Dying Light 2: Reloaded Edition",
        "Lumberhill",
        "Craftopia",
        "World of Tanks",
        "The Sims\\u2122 4",
        "Metro: Last Light Complete Edition"
      ]
    },
    {
      "username": "aocaa1267",
      "password": "qazqaz123@#",
      "country": "KW",
      "games": [
        "The Forest",
        "Assetto Corsa",
        "Grand Theft Auto V",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest",
        "Fishing Planet",
        "Wallpaper Engine",
        "SCUM",
        "Friday the 13th: The Game",
        "Paunch",
        "Hand Simulator: Survival",
        "Pacify",
        "Apex Legends",
        "Red Dead Redemption 2",
        "DEVOUR",
        "Redmatch 2",
        "Hello Neighbor 2 Alpha 1",
        "BEACHED",
        "Gas Station Simulator: Prologue - Early Days",
        "Forza Horizon 5",
        "Lunch Lady",
        "3D Aim Trainer",
        "Muck",
        "Animal Shelter: Prologue",
        "Car Detailing Simulator: Prologue",
        "Captain Bones: Prologue",
        "TEST RE",
        "MultiVersus",
        "DogeFight",
        "Inside the Backrooms",
        "Gravewood High",
        "Call of Duty\\u00ae",
        "Dota 2",
        "Source SDK Base 2007",
        "Spacewar",
        "Sniper Elite 4 Dedicated Server"
      ]
    },
    {
      "username": "Brayab12",
      "password": "milagrosariana7@",
      "country": "PE",
      "games": [
        "Warframe",
        "Unturned",
        "eFootball PES 2021 SEASON UPDATE",
        "Little Nightmares",
        "Call of Juarez Gunslinger",
        "Mafia",
        "Call of Duty\\u00ae",
        "Metro: Last Light Complete Edition",
        "Dota 2"
      ]
    },
    {
      "username": "bofa20133",
      "password": "2882003Nhan",
      "country": "VN",
      "games": [
        "FreeStyle 2: Street Basketball",
        "\\u9f99\\u9b42\\u65f6\\u523b",
        "Cube Racer",
        "Counter-Strike 2"
      ]
    },
    {
      "username": "rosesareblack142",
      "password": "Blackrosedragon241",
      "country": "IQ",
      "games": [
        "Unturned",
        "Yu-Gi-Oh!  Master Duel"
      ]
    },
    {
      "username": "althebad",
      "password": "parkourkiller334",
      "country": "ES",
      "games": [
        "Garry's Mod",
        "Commandos 3: Destination Berlin",
        "Left 4 Dead 2",
        "Arma 2",
        "Arma 2: Operation Arrowhead",
        "Cities in Motion",
        "Darkest Hour: A Hearts of Iron Game",
        "Painkiller: Black Edition",
        "Warlock - Master of the Arcane",
        "Counter-Strike 2",
        "LEGO\\u00ae The Lord of the Rings\\u2122",
        "Bloodline Champions",
        "Neverwinter",
        "Warframe",
        "War Thunder",
        "Path of Exile",
        "Arma 2: DayZ Mod",
        "The Forest",
        "Gun Monkeys",
        "R.I.P.D.: The Game",
        "Saints Row 2",
        "Risen 2 - Dark Waters",
        "Saints Row: The Third",
        "Sacred 2 Gold",
        "Gothic Playable Teaser",
        "Saints Row IV",
        "Takedown: Red Sabre",
        "Cube &amp; Star: An Arbitrary Love",
        "Canyon Capers",
        "Real Horror Stories Ultimate Edition",
        "Echo of Soul",
        "Deponia: The Complete Journey",
        "Numba Deluxe",
        "Unturned",
        "Minimum",
        "Simply Chess",
        "The Sun at Night",
        "NARUTO SHIPPUDEN: Ultimate Ninja STORM Revolution",
        "Heavy Metal Machines",
        "Pixel Puzzles 2: Anime",
        "Pixel Puzzles Illustrations &amp; Anime",
        "Pixel Puzzles Traditional Jigsaws",
        "Survarium",
        "Eron",
        "Killing Floor 2",
        "The Elder Scrolls: Legends",
        "Ghost in the Shell: Stand Alone Complex - First Assault Online",
        "Dead by Daylight",
        "SMITE",
        "SMITE - Public Test",
        "Mitos.is: The Game",
        "The Prism",
        "Dying Light",
        "Paladins",
        "Paladins - Public Test",
        "Evolve Stage 2",
        "Five Nights at Freddy's: Sister Location",
        "Golf It!",
        "PUBG: BATTLEGROUNDS",
        "PAYDAY 2",
        "Soul at Stake - 1v4",
        "Casinopia: The Blackjack",
        "Hotel Dracula",
        "Deceit",
        "Battlerite Public Test",
        "Battlerite",
        "Aimtastic",
        "Tom Clancy's Rainbow Six Siege",
        "Tom Clancy's Rainbow Six Siege - Test Server",
        "Project Pastorate",
        "When They Arrived",
        "KurtzPel",
        "Falling words",
        "JUST DASH",
        "Among Us",
        "Eternal Return",
        "Fall Guys",
        "Strinova",
        "Action Taimanin",
        "Yu-Gi-Oh!  Master Duel",
        "Omega Strikers",
        "Brotato",
        "SNOWBREAK",
        "Team Fortress 2",
        "Dota 2"
      ]
    },
    {
      "username": "dnqob25782",
      "password": "tAHA@142001",
      "country": "CN",
      "games": [
        "Counter-Strike 2",
        "eFootball\\u2122",
        "NARAKA: BLADEPOINT",
        "EA SPORTS FC\\u2122 25",
        "Spacewar"
      ]
    },
    {
      "username": "combativescrawnyoctopus",
      "password": "Megagrain32",
      "country": "US",
      "games": [
        "Counter-Strike 2",
        "Dota Underlords",
        "Apex Legends",
        "POSTAL",
        "eFootball\\u2122",
        "Lost Ark",
        "Greed of Man",
        "Dota 2",
        "Source SDK Base 2007"
      ]
    },
    {
      "username": "Sattra25431",
      "password": "sattra2543",
      "country": "TH",
      "games": [
        "Alien Shooter",
        "PlanetSide 2",
        "PlanetSide 2 - Test",
        "War Thunder",
        "The Forest",
        "Cities: Skylines",
        "PUBG: BATTLEGROUNDS",
        "Sniper Ghost Warrior 3",
        "Ring of Elysium",
        "Ironsight",
        "Green Hell",
        "Apex Legends",
        "Need for Speed\\u2122 Most Wanted",
        "World of Tanks",
        "MIR4",
        "eFootball\\u2122",
        "GUNDAM EVOLUTION",
        "ARK: Survival Evolved",
        "ARK: Survival Of The Fittest"
      ]
    },
    {
      "username": "glader200",
      "password": "148635279As",
      "country": "TR",
      "games": [
        "Warframe",
        "Assetto Corsa",
        "PAYDAY 2",
        "Brawlhalla",
        "The Witcher 3: Wild Hunt",
        "World of Warships",
        "Counter-Strike 2",
        "Destiny 2",
        "Apex Legends",
        "World of Tanks",
        "3D Aim Trainer",
        "eFootball\\u2122",
        "Halo Infinite",
        "PUBG: BATTLEGROUNDS",
        "VEILED EXPERTS",
        "THE FINALS",
        "World War 3",
        "Call of Duty\\u00ae",
        "Combat Master",
        "NARAKA: BLADEPOINT"
      ]
    }
  ];